In [16]:
import pandas as pd
data = pd.read_excel('data_train_not_nans.xlsx')
data

,Unnamed: 0,event_date,longitude,latitude,landslide_category,landslide_trigger,landslide_size,precipitation-1,pressure-1,humidity-1,...,humidity-118,temp-118,precipitation-119,pressure-119,humidity-119,temp-119,precipitation-120,pressure-120,humidity-120,temp-120
0,1,2009-01-02 02:00:00,-122.663000,45.420000,mudslide,downpour,small,6.847097,99.318387,4.135806,...,5.313667,7.210667,5.413548,98.300645,4.990645,5.142258,12.827143,98.260000,4.919643,4.009286
1,3,2009-07-31 00:00:00,81.708000,28.837800,landslide,monsoon,medium,7.704194,76.833226,14.522581,...,6.714194,13.080000,1.235333,77.200667,12.853000,17.194667,1.920000,76.942903,13.216129,18.455161
2,4,2010-10-16 12:00:00,123.897800,10.333600,landslide,tropical_cyclone,medium,10.500645,99.705161,19.056774,...,18.634516,26.195484,7.504194,99.643226,19.243226,26.436452,6.550667,99.621667,19.426667,26.864333
3,5,2012-02-16 00:00:00,124.966800,10.700400,landslide,downpour,medium,17.905517,99.595172,18.382414,...,18.734194,27.695484,4.414000,99.619333,18.218667,26.921667,6.939677,99.695484,17.570000,25.808710
4,6,2012-03-30 00:00:00,-117.266500,48.279700,mudslide,downpour,small,4.858065,89.854194,3.721290,...,7.474667,15.163000,2.016774,90.449355,5.494516,8.362903,1.505667,90.433000,4.138333,3.631333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,11028,2017-04-01 13:34:00,111.679944,-7.853409,landslide,rain,medium,8.779333,98.052000,18.270000,...,15.215806,24.273871,1.761000,97.948000,16.845000,24.503667,1.889355,98.055806,18.061935,25.445806
9990,11029,2017-03-25 17:32:00,75.680611,33.403080,landslide,other,small,2.617742,71.468065,4.351290,...,8.111000,15.797000,1.156774,71.642903,6.477419,11.677742,0.079000,71.805000,5.726667,9.142667
9991,11030,2016-12-15 05:00:00,91.772042,26.181606,landslide,unknown,small,0.092258,96.836774,10.805161,...,8.496774,20.340323,2.868214,96.837143,8.521429,16.315714,0.053226,97.056452,6.952903,14.040000
9992,11031,2017-04-29 19:03:00,73.472379,40.886395,translational_slide,downpour,large,2.119333,78.571000,4.770667,...,5.654516,18.256129,0.278667,78.245667,5.666333,17.168000,1.183871,78.588387,5.656774,11.794839
9993,11032,2017-03-13 14:32:00,78.356505,17.465630,mudslide,construction,small,0.325161,94.658387,7.101290,...,16.715333,27.801333,0.630323,94.182903,10.926452,33.652581,0.699667,94.498667,9.733333,31.778667

In [2]:
reduced_df = pd.read_excel('pca_df.xlsx')
reduced_df

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16,PC17,PC18,PC19,PC20
0,2.768696,12.667523,0.411167,2.857535,4.027263,-4.994954,3.366948,-0.115972,-1.899430,0.386918,0.107896,-0.800178,-0.071395,-0.369904,0.006501,0.798476,-0.016250,0.645267,-0.514079,0.856809
1,16.082377,-12.845456,-5.202100,-1.907500,-0.821905,-0.870091,0.802201,2.524230,0.421631,-1.610605,-1.150725,-0.894827,0.397319,0.238378,-0.834879,-0.800614,-0.276008,0.602286,-0.658578,1.018544
2,-23.173111,-5.290416,0.899408,2.005395,-2.982593,-0.729501,0.320674,-3.547957,2.326039,-0.839094,-0.130267,-0.212209,-0.358118,-0.042970,-0.380264,-0.428369,0.267509,1.320467,-1.959103,0.260211
3,-25.548555,-6.124633,5.522850,2.543240,1.761109,3.466775,4.149016,-0.001661,-3.371339,0.061936,0.423617,-1.683376,2.957564,0.481411,0.553302,-0.090525,-0.281168,0.441334,2.130071,0.058763
4,14.195970,10.109598,5.356651,-3.538066,-4.099286,-1.796769,5.100535,-0.808471,0.620037,-0.401894,-1.515657,2.388069,0.134567,0.621448,-0.278377,0.283955,-0.426441,0.608450,0.695287,0.243795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,-19.967703,-5.516079,0.948872,6.533998,-4.228811,3.000546,5.732345,-1.882050,1.643050,0.796374,-0.191219,-0.776465,0.749121,-0.129468,-0.454173,0.636215,-0.176336,-1.961471,-0.490201,-0.876784
9990,24.268872,-8.220326,12.475897,-4.438803,-2.829333,-5.040561,1.971380,0.441247,-2.379538,-0.355688,-0.219213,-0.583461,0.657783,1.119803,-0.639377,0.313232,-0.844416,-0.276166,-0.051608,-0.587759
9991,-15.146782,0.386949,15.532330,9.136227,-2.172533,7.018825,-8.016906,4.572874,0.700317,-1.597150,1.112955,1.517327,0.735736,-0.411788,-1.158861,0.945385,-1.063665,0.644032,-0.371555,-1.527478
9992,23.634228,-1.789336,4.281199,-5.590769,-6.800842,-0.741137,2.937817,0.479025,-0.593656,-0.667507,0.693727,3.466802,-0.080797,-0.272508,0.208063,0.612109,-0.184291,0.214979,-0.206873,0.300717
9993,-10.229515,-1.588400,6.116982,-5.743987,-7.361080,-1.381627,-9.433882,1.824552,-3.470304,1.131300,5.149119,-2.931418,-0.255565,0.692594,0.218135,0.606297,0.895467,-0.843220,0.768047,-0.578588

In [12]:
import pandas as pd
data_ = pd.read_excel('data.xlsx')
data_

,event_date,location_accuracy,landslide_category,landslide_trigger,landslide_size,landslide_setting,fatality_count,longitude,latitude,number
0,08/01/2008 12:00:00 AM,unknown,landslide,rain,large,mine,11.0,107.450000,32.562500,1
1,01/02/2009 02:00:00 AM,5km,mudslide,downpour,small,unknown,0.0,-122.663000,45.420000,2
2,01/19/2007 12:00:00 AM,10km,landslide,downpour,large,unknown,10.0,-75.358700,-11.129500,3
3,07/31/2009 12:00:00 AM,unknown,landslide,monsoon,medium,unknown,1.0,81.708000,28.837800,4
4,10/16/2010 12:00:00 PM,5km,landslide,tropical_cyclone,medium,unknown,0.0,123.897800,10.333600,5
...,...,...,...,...,...,...,...,...,...,...
11028,04/01/2017 01:34:00 PM,5km,landslide,rain,medium,natural_slope,27.0,111.679944,-7.853409,11029
11029,03/25/2017 05:32:00 PM,5km,landslide,other,small,natural_slope,2.0,75.680611,33.403080,11030
11030,12/15/2016 05:00:00 AM,1km,landslide,unknown,small,urban,1.0,91.772042,26.181606,11031
11031,04/29/2017 07:03:00 PM,1km,translational_slide,downpour,large,natural_slope,24.0,73.472379,40.886395,11032
11032,03/13/2017 02:32:00 PM,1km,mudslide,construction,small,urban,2.0,78.356505,17.465630,11033

In [3]:
data_['landslide_setting']

array(['mine', 'unknown', 'above_road', 'urban', 'natural_slope', nan,
       'engineered_slope', 'below_road', 'above_river', 'retaining_wall',
       'other', 'above_coast', 'bluff', 'burned_area', 'deforested_slope'],
      dtype=object)

In [27]:
import pandas as pd
data_0 = pd.read_csv('Global_Landslide_Catalog_Export.csv')
data_0

,source_name,source_link,event_id,event_date,event_time,event_title,event_description,location_description,location_accuracy,landslide_category,...,country_code,admin_division_name,admin_division_population,gazeteer_closest_point,gazeteer_distance,submitted_date,created_date,last_edited_date,longitude,latitude
0,AGU,https://blogs.agu.org/landslideblog/2008/10/14...,684,08/01/2008 12:00:00 AM,NaN,"Sigou Village, Loufan County, Shanxi Province","occurred early in morning, 11 villagers buried...","Sigou Village, Loufan County, Shanxi Province",unknown,landslide,...,CN,Shaanxi,0.0,Jingyang,41.02145,04/01/2014 12:00:00 AM,11/20/2017 03:17:00 PM,02/15/2018 03:51:00 PM,107.450000,32.562500
1,Oregonian,http://www.oregonlive.com/news/index.ssf/2009/...,956,01/02/2009 02:00:00 AM,NaN,"Lake Oswego, Oregon",Hours of heavy rain are to blame for an overni...,"Lake Oswego, Oregon",5km,mudslide,...,US,Oregon,36619.0,Lake Oswego,0.60342,04/01/2014 12:00:00 AM,11/20/2017 03:17:00 PM,02/15/2018 03:51:00 PM,-122.663000,45.420000
2,CBS News,https://www.cbsnews.com/news/dozens-missing-af...,973,01/19/2007 12:00:00 AM,NaN,"San Ramon district, 195 miles northeast of the...",(CBS/AP) At least 10 people died and as many a...,"San Ramon district, 195 miles northeast of the...",10km,landslide,...,PE,Junín,14708.0,San Ramón,0.85548,04/01/2014 12:00:00 AM,11/20/2017 03:17:00 PM,02/15/2018 03:51:00 PM,-75.358700,-11.129500
3,Reuters,https://in.reuters.com/article/idINIndia-41450...,1067,07/31/2009 12:00:00 AM,NaN,Dailekh district,"One person was killed in Dailekh district, pol...",Dailekh district,unknown,landslide,...,NP,Mid Western,20908.0,Dailekh,0.75395,04/01/2014 12:00:00 AM,11/20/2017 03:17:00 PM,02/15/2018 03:51:00 PM,81.708000,28.837800
4,The Freeman,http://www.philstar.com/cebu-news/621414/lands...,2603,10/16/2010 12:00:00 PM,NaN,sitio Bakilid in barangay Lahug,Another landslide in sitio Bakilid in barangay...,sitio Bakilid in barangay Lahug,5km,landslide,...,PH,Central Visayas,798634.0,Cebu City,2.02204,04/01/2014 12:00:00 AM,11/20/2017 03:17:00 PM,02/15/2018 03:51:00 PM,123.897800,10.333600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11028,The Jakarta Post,http://www.thejakartapost.com/news/2017/04/02/...,11109,04/01/2017 01:34:00 PM,NaN,Major landslide in Banaran,Landslide exacerbated by deforestation and bad...,"Banaran, Ponorogo, Jawa Timur, Indonesia",5km,landslide,...,NaN,NaN,NaN,NaN,NaN,07/28/2017 01:34:00 PM,12/19/2017 09:42:00 PM,02/15/2018 03:51:00 PM,111.679944,-7.853409
11029,Greater Kashmir,http://www.greaterkashmir.com/news/jammu/lands...,10845,03/25/2017 05:32:00 PM,NaN,Barnari Sigdi Landslide,Two teenage girls died after they were buried ...,"Barnari Sigdi area, Tehsil Mughalmaidan, Kisht...",5km,landslide,...,NaN,NaN,NaN,NaN,NaN,09/21/2017 05:32:00 PM,12/05/2017 06:45:00 PM,02/15/2018 03:51:00 PM,75.680611,33.403080
11030,NBC Daily,http://www.nbcdaily.com/separate-landslides-ki...,10973,12/15/2016 05:00:00 AM,NaN,Landslide at Pub Sarania Hill,An octogenarian was killed when a sudden lands...,"Pub Sarania Hill, Guwahati, Assam, India",1km,landslide,...,NaN,NaN,NaN,NaN,NaN,07/26/2017 01:22:00 PM,12/08/2017 08:37:00 PM,02/15/2018 03:51:00 PM,91.772042,26.181606
11031,AGU Landslide Blog,http://blogs.agu.org/landslideblog/2017/05/02/...,10901,04/29/2017 07:03:00 PM,NaN,Mayor landslide at Ayu village,Landslide triggered by heavy rainfall buried 1...,"Ayu, Ozgon, Osh, Kyrgyzstan",1km,translational_slide,...,NaN,NaN,NaN,NaN,NaN,07/14/2017 07:03:00 PM,12/07/2017 09:19:00 PM,02/15/2018 03:51:00 PM,73.472379,40.886395
11032,The Times of India,https://timesofindia.indiatimes.com/city/hyder...,10949,03/13/2017 02:32:00 PM,NaN,Kondapur Commercial Complex Construction Mudslide,A mudslide at an under-construction commercial...,"Hyderabad, Rangareddy, Telangana",1km,mudslide,...,NaN,NaN,NaN,NaN,NaN,10/05/2017 02:32:00 PM,12/08/2017 07:57:00 PM,02/15/2018 03:51:00 PM,78.356505,17.465630

In [28]:
ggg = data_0.dropna()
ggg

Empty DataFrame
Columns: [source_name, source_link, event_id, event_date, event_time, event_title, event_description, location_description, location_accuracy, landslide_category, landslide_trigger, landslide_size, landslide_setting, fatality_count, injury_count, storm_name, photo_link, notes, event_import_source, event_import_id, country_name, country_code, admin_division_name, admin_division_population, gazeteer_closest_point, gazeteer_distance, submitted_date, created_date, last_edited_date, longitude, latitude]
Index: []

[0 rows x 31 columns]

In [25]:
data['landslide_setting'] = ggg['landslide_setting']

KeyError: 'landslide_setting'

In [ ]:
data.to_excel('data_train_not_nans.xlsx', index=False)

In [5]:
data['landslide_trigger'].value_counts()

downpour                   4680
rain                       2592
unknown                    1691
continuous_rain             748
tropical_cyclone            561
snowfall_snowmelt           135
monsoon                     129
mining                       93
earthquake                   89
construction                 82
flooding                     75
no_apparent_trigger          44
freeze_thaw                  41
other                        26
dam_embankment_collapse      12
leaking_pipe                 10
volcano                       1
vibration                     1
Name: landslide_trigger, dtype: int64

In [10]:
# Объединение DataFrame `data` и `reduced_df`
combined_df = pd.concat([data[['longitude', 'latitude', 'landslide_category', 'landslide_trigger', 'landslide_size']], reduced_df], axis=1)

In [13]:
combined_df.to_excel('data_to_train.xlsx', index=False)